export const productBoy=[
    //------------clothes/blouses
    {
        id: 1,
        title: 'blouse-boy-1',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'clothes',
        subcategory: 'blouses',
        price: '488,000 تومان',
        img: './images/image-boys/clothes/blouses/blouse-boy-1.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },
      {
        id: 2,
        title: 'blouse-boy-2',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'clothes',
        subcategory: 'blouses',
        price: '488,000 تومان',
        img: './images/image-boys/clothes/blouses/blouse-boy-2.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },
      {
        id: 3,
        title: 'blouse-boy-3',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'clothes',
        subcategory: 'blouses',
        price: '488,000 تومان',
        img: './images/image-boys/clothes/blouses/blouse-boy-3.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },
      {
        id: 4,
        title: 'blouse-boy-4',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'clothes',
        subcategory: 'blouses',
        price: '488,000 تومان',
        img: './images/image-boys/clothes/blouses/blouse-boy-4.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },
      {
        id: 5,
        title: 'blouse-boy-5',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'clothes',
        subcategory: 'blouses',
        price: '488,000 تومان',
        img: './images/image-boys/clothes/blouses/blouse-boy-5.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },
      {
        id: 6,
        title: 'blouse-boy-6',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'clothes',
        subcategory: 'blouses',
        price: '488,000 تومان',
        img: './images/image-boys/clothes/blouses/blouse-boy-6.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },
      {
        id: 7,
        title: 'blouse-boy-7',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'clothes',
        subcategory: 'blouses',
        price: '488,000 تومان',
        img: './images/image-boys/clothes/blouses/blouse-boy-7.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      }, 
    //------------clothes/pants
    {
      id: 8,
      title: 'pants-boy-1',
      subtitle:'پیراهن انگلیسی',
      category: 'boys',
      maincategory: 'clothes',
      subcategory: 'pants',
      price: '488,000 تومان',
      img: './images/image-boys/clothes/pants/pants-boy-1.jpg',
      desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
      material:'لینن'
    }, 
    {
      id: 9,
      title: 'pants-boy-2',
      subtitle:'پیراهن انگلیسی',
      category: 'boys',
      maincategory: 'clothes',
      subcategory: 'pants',
      price: '488,000 تومان',
      img: './images/image-boys/clothes/pants/pants-boy-2.jpg',
      desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
      material:'لینن'
    },  
    {
      id: 10,
      title: 'pants-boy-3',
      subtitle:'پیراهن انگلیسی',
      category: 'boys',
      maincategory: 'clothes',
      subcategory: 'pants',
      price: '488,000 تومان',
      img: './images/image-boys/clothes/pants/pants-boy-3.jpg',
      desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
      material:'لینن'
    }, 
    {
      id: 11,
      title: 'pants-boy-4',
      subtitle:'پیراهن انگلیسی',
      category: 'boys',
      maincategory: 'clothes',
      subcategory: 'pants',
      price: '488,000 تومان',
      img: './images/image-boys/clothes/pants/pants-boy-4.jpg',
      desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
      material:'لینن'
    },
    //------------clothes/setclothes  
    {
      id: 12,
      title: 'setclothe-boy-1',
      subtitle:'پیراهن انگلیسی',
      category: 'boys',
      maincategory: 'clothes',
      subcategory: 'setclothes',
      price: '488,000 تومان',
      img: './images/image-boys/clothes/setclothes/setclothe-boy-1.jpg',
      desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
      material:'لینن'
    }, 
    {
      id: 13,
      title: 'setclothe-boy-2',
      subtitle:'پیراهن انگلیسی',
      category: 'boys',
      maincategory: 'clothes',
      subcategory: 'setclothes',
      price: '488,000 تومان',
      img: './images/image-boys/clothes/setclothes/setclothe-boy-2.jpg',
      desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
      material:'لینن'
    },
    {
      id: 14,
      title: 'setclothe-boy-3',
      subtitle:'پیراهن انگلیسی',
      category: 'boys',
      maincategory: 'clothes',
      subcategory: 'setclothes',
      price: '488,000 تومان',
      img: './images/image-boys/clothes/setclothes/setclothe-boy-3.jpg',
      desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
      material:'لینن'
    }, 
    {
      id: 15,
      title: 'setclothe-boy-4',
      subtitle:'پیراهن انگلیسی',
      category: 'boys',
      maincategory: 'clothes',
      subcategory: 'setclothes',
      price: '488,000 تومان',
      img: './images/image-boys/clothes/setclothes/setclothe-boy-4.jpg',
      desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
      material:'لینن'
    }, 
      //------------shoes 
      {
        id: 16,
        title: 'kafsh-boy-1',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'shoes',
        subcategory: '',
        price: '488,000 تومان',
        img: './images/image-boys/shoes/kafsh-boy-1.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      }, 
      {
        id: 17,
        title: 'kafsh-boy-2',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'shoes',
        subcategory: '',
        price: '488,000 تومان',
        img: './images/image-boys/shoes/kafsh-boy-2.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },
      {
        id: 18,
        title: 'kafsh-boy-3',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'shoes',
        subcategory: '',
        price: '488,000 تومان',
        img: './images/image-boys/shoes/kafsh-boy-3.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      }, 
      {
        id: 19,
        title: 'kafsh-boy-4',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'shoes',
        subcategory: '',
        price: '488,000 تومان',
        img: './images/image-boys/shoes/kafsh-boy-4.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },
      {
        id: 20,
        title: 'kafsh-boy-5',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'shoes',
        subcategory: '',
        price: '488,000 تومان',
        img: './images/image-boys/shoes/kafsh-boy-5.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      }, 
      {
        id: 21,
        title: 'kafsh-boy-6',
        subtitle:'پیراهن انگلیسی',
        category: 'boys',
        maincategory: 'shoes',
        subcategory: '',
        price: '488,000 تومان',
        img: './images/image-boys/shoes/kafsh-boy-6.jpg',
        desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
        material:'لینن'
      },               
    ]
