export const productGirl=[
//------------clothes/shirts------
{
    id: 1,
    title: 'shirt-girl-1',
    subtitle:'پیراهن انگلیسی',
    category: 'girls',
    maincategory: 'clothes',
    subcategory: 'shirts',
    price: '488,000 تومان',
    img: './images/image-girls/clothes/shirts/shirt-girl-1.jpg',
    desc: `کش دوزی در قسمت سینه/ استین کوتاه/ دور یقه مغزی دوزی شده/ بسیار سبک و نرم/ مناسب مراسمات رسمی و روزمره `,
    material:'لینن'
  },
  {
    id: 2,
    title: 'shirt-girl-2',
    subtitle:' پیراهن فروغ',
    category: 'girls',
    maincategory: 'clothes',
    subcategory: 'shirts',
    price: '490,000 تومان',
    img: './images/image-girls/clothes/shirts/shirt-girl-2.jpg',
    desc: `یقه ایستاده لب چین دار/بسیار خوش جنس و ایست دار/چین دار از قسمت زیر پیش سینه/ دارای گلدوزی در قسمت پیش سینه/ نواردوزی شده در قسمت دور گلدوزی/مناسب مراسم و مهمانی ها `,
    material:'لینن گرماژ بالا'
  },
  {
    id: 3,
    title: 'shirt-girl-3',
    subtitle:' پیراهن آریس ',
    category: 'girls',
    maincategory: 'clothes',
    subcategory: 'shirts',
    price: '650,000 تومان',
    img: './images/image-girls/clothes/shirts/shirt-girl-3.jpg',
    desc:'یقه ب ب/ آستین حلقه ای/ کمر پیله دار/ مناسب مراسم های رسمی',
    material:'ژاکارد '
  },
  {
    id: 4,
    title: 'shirt-girl-4',
    subtitle: 'پیراهن رانا',
    category: 'girls',
    maincategory: 'clothes',
    subcategory: 'shirts',
    price: '269,000 تومان',
    img: './images/image-girls/clothes/shirts/shirt-girl-4.jpg',
    desc:'یقه گرد / دور کمرچین سوزنی کش دوزی شده/ آستین بلند لبه دار با بند قابل تنظیم/ مناسب استفاده روزمره و مهمانی ها',
    material:'جین کاغذی '
  },
  {
  id: 5,
  title: 'shirt-girl-5',
  subtitle: 'پیراهن پایین تور السا',
  category: 'girls',
  maincategory: 'clothes',
  subcategory: 'shirts',
  price: '329,000 تومان',
  img: './images/image-girls/clothes/shirts/shirt-girl-5.jpg',
  desc:'یقه گرد/ آستین کوتاه چین دار از سرشانه/ طرح چاپ السا شخصیت مورد علاقه کودکان در بالا تنه پیراهن/ بسیار سبک و نرم و راحت/ مناسب  فصول بهار و تابستان',
  material:'نخ پنبه لاکرا دار'
},
{
id: 6,
title: 'shirt-girl-6',
subtitle: 'پیراهن پایین تور السا',
category: 'girls',
maincategory: 'clothes',
subcategory: 'shirts',
price: '329,000 تومان',
img: './images/image-girls/clothes/shirts/shirt-girl-6.jpg',
desc:'یقه گرد/ آستین کوتاه چین دار از سرشانه/ طرح چاپ السا شخصیت مورد علاقه کودکان در بالا تنه پیراهن/ بسیار سبک و نرم و راحت/ مناسب  فصول بهار و تابستان',
material:'نخ پنبه لاکرا دار'
},
{
id: 7,
title: 'shirt-girl-7',
subtitle: ' پیراهن امی',
category: 'girls',
maincategory: 'clothes',
subcategory: 'shirts',
price: '527,000 تومان',
img: './images/image-girls/clothes/shirts/shirt-girl-7.jpg',
desc:'یقه گرد/ چین دار از سرشانه تا کمر و در امتداد پشت پیراهن/ کمر دارای چین های ریز/ دارای رنگ زیبا و نئون/ مناسب بهار و تابستان',
material:'آمبرودی (خامه دوزی)'
},
{
id: 8,
title: 'shirt-girl-8',
subtitle: ' پیراهن دونا',
category: 'girls',
maincategory: 'clothes',
subcategory: 'shirts',
price: '890,000 تومان',
img: './images/image-girls/clothes/shirts/shirt-girl-8.jpg',
desc:' یقه گرد/آستین حلقه ای با لبه های توری/ چین دار از کمر/ دارای تور ضخیم در قسمت داخلی انتهایی برای پف ایستادن پیراهن/ جنس کمر از ساتن با دیتیل پاپیون/ مناسب مراسم رسمی',
material:'ساتن آمریکایی'
},
{
  id: 9,
  title: 'shirt-girl-9',
  subtitle: ' پیراهن پاپاتیا',
  category: 'girls',
  maincategory: 'clothes',
  subcategory: 'shirts',
  price: '329,000 تومان',
  img: './images/image-girls/clothes/shirts/shirt-girl-9.jpg',
  desc:'پیراهن آستین حلقه ای و یقه گرد/ چین دار از کمر/ مناسب مراسم های رسمی و دید و بازدید های نوروز ' ,
  material:'نخ پنبه لاکرا دار'
  },
  {
    id: 10,
    title: 'shirt-girl-10',
    subtitle: ' پیراهن تانیل ',
    category: 'girls',
    maincategory: 'clothes',
    subcategory: 'shirts',
    price: '329,000 تومان',
    img: './images/image-girls/clothes/shirts/shirt-girl-10.jpg',
    desc:' یقه گرد/ سر آستین ها و دور یقه و انتهای قسمت بالا تنه کش بافت/بسیار راحت، نرم و سبک/ قابلیت استفاده روزمره و مراسم و مهمانی ها',
    material:'نخ پنبه لاکرا دار'
    },
//------------clothes/blouses-------
{
  id: 11,
  title: 'blouse-girl-1',
  subtitle: ' هودی کایلی ',
  category: 'girls',
  maincategory: 'clothes',
  subcategory: 'blouses',
  price: '290,000 تومان',
  img: './images/image-girls/clothes/blouses/blouse-girl-1.jpg',
  desc:'کلاه دار/ آستین بلند/ سرشانه افتاده/ سر آستین و انتهای هودی کش بافت/ بسیار احت و با دوام/مناسب ست شدن با انواع شلوار جین و کتان/ مناسب فصول سرد سال',
  material:'دورس دو نخ لاکرا دار'
  },
  {
    id: 12,
    title: 'blouse-girl-2',
    subtitle: 'هودی لورا ',
    category: 'girls',
    maincategory: 'clothes',
    subcategory: 'blouses',
    price: '290,000 تومان',
    img: './images/image-girls/clothes/blouses/blouse-girl-2.jpg',
    desc:'کلاه دار/ آستین بلند/ سرشانه افتاده/ سر آستین و انتهای هودی کش بافت/ بسیار احت و با دوام/مناسب ست شدن با انواع شلوار جین و کتان/ مناسب فصول سرد سال',
    material:'دورس دو نخ لاکرا دار'
    },
//------------clothes/pants-------
  {
    id: 13,
    title: 'pants-girl-1',
    subtitle:  'شلوار جین 015' ,
    category: 'girls',
    maincategory: 'clothes',
    subcategory: 'pants',
    price: '275,000 تومان',
    img: './images/image-girls/clothes/pants/pants-girl-1.jpg',
    desc:'دارای بند قابل تنظیم/ کمر کش و قابل تنظیم/ پایین شلوار کش دوزی شده/ دارای دو جیب از پهلو/ بسیار خوش جنس و با دوام',
    material:'نخ  پنبه'
    },
    {
      id: 14,
      title: 'pants-girl-2',
      subtitle:  'شلوار دو رنگ  ' ,
      category: 'girls',
      maincategory: 'clothes',
      subcategory: 'pants',
      price: '275,000 تومان',
      img: './images/image-girls/clothes/pants/pants-girl-2.jpg',
      desc:'دارای بند قابل تنظیم/ کمر کش و قابل تنظیم/ پایین شلوار کش دوزی شده/ دارای دو جیب از پهلو/ بسیار خوش جنس و با دوام',
      material:'نخ  پنبه'
      },
    {
      id: 15,
      title: 'pants-girl-3',
      subtitle:  'شلوار جین 001' ,
      category: 'girls',
      maincategory: 'clothes',
      subcategory: 'pants',
      price: '209,000 تومان',
      img: './images/image-girls/clothes/pants/pants-girl-3.jpg',
      desc:'دارای بند قابل تنظیم/ کمر کش و قابل تنظیم/ پایین شلوار کش دوزی شده/ دارای دو جیب از پهلو/ بسیار خوش جنس و با دوام',
      material:'نخ  پنبه'
      },
      {
        id: 16,
        title: 'pants-girl-4',
        subtitle:  'شلوار دو رنگ  ' ,
        category: 'girls',
        maincategory: 'clothes',
        subcategory: 'pants',
        price: '209,000 تومان',
        img: './images/image-girls/clothes/pants/pants-girl-4.jpg',
        desc:'دارای بند قابل تنظیم/ کمر کش و قابل تنظیم/ پایین شلوار کش دوزی شده/ دارای دو جیب از پهلو/ بسیار خوش جنس و با دوام',
        material:'نخ  پنبه'
        },  
        {
          id: 17,
          title: 'pants-girl-5',
          subtitle:  'شلوار دو رنگ  ' ,
          category: 'girls',
          maincategory: 'clothes',
          subcategory: 'pants',
          price: '209,000 تومان',
          img: './images/image-girls/clothes/pants/pants-girl-5.jpg',
          desc:'دارای بند قابل تنظیم/ کمر کش و قابل تنظیم/ پایین شلوار کش دوزی شده/ دارای دو جیب از پهلو/ بسیار خوش جنس و با دوام',
          material:'نخ  پنبه'
          }, 
//------------shoes-------   
        {
          id: 18,
          title: 'kafsh-girl-1.jpg',
          subtitle:  'کفش نیل ' ,
          category: 'girls',
          maincategory: 'shoes',
          subcategory: '',
          price: '355,000 تومان',
          img: './images/image-girls/shoes/kafsh-girl-1.jpg',
          desc:'دارای رویه نرم و مقاوم از جنس ورنی با طرح پاپیون اسکارلت در قسمت جلوی کفش  و زیره ضد سایش و ضد لغزش، دارای بند چسبی در قسمت رویه جهت پوشیدن راحت تر و تنظیم راحت تر، فوق العاده سبک، راحت و بادوام. ',
          material:'نوعی کفش تخت  '
          },
          {
            id: 19,
            title: 'kafsh-girl-2.jpg',
            subtitle:  'کفش آماندا  ' ,
            category: 'girls',
            maincategory: 'shoes',
            subcategory: '',
            price: '349,000 تومان',
            img: './images/image-girls/shoes/kafsh-girl-2.jpg',
            desc:' دارای رویه نرم و لطیف از جنس ساتن با دوختهای سراسری جهت افزایش استحکام /  باز بودن قسمت انتهایی کفش برای جذابیت بیشتر کفش/ دارا بودن نگین بسیار زیبا و با کیفیت بدون ریزش و تغییر رنگ، روی کفش /بسیار با دوام و سبک/مناسب استفاده و ست شدن با انواع پیراهن مجلسی ',
            material:'نوعی کفش تخت  '
            }, 
            {
              id: 20,
              title: 'kafsh-girl-3.jpg',
              subtitle:  'پوتین مینی موس ورنی  ' ,
              category: 'girls',
              maincategory: 'shoes',
              subcategory: '',
              price: '355,000 تومان',
              img: './images/image-girls/shoes/kafsh-girl-3.jpg',
              desc:'دارای رویه با کیفیت از جنس ورنی/ طرح استیکر مینی موس/دارای بند همرا با زیپ برای سهولت در استفاده کودکان/داخل کار عایق بندی شده که مانع از ورود آب و رطوبت به داخل پوتین میشود/زیره ضد سایش و ضد لغزش به دلیل ناهمواری در قسمت تحتانی مانع لیز خوردن کفش در محیط های مرطوب میشود/زیره دوخته شده به رویه جهت افزایش استحکام کفش در بلند مدت',
              material:' نوعی پوتین ورنی است   '
              },
              {
                id: 21,
                title: 'kafsh-girl-4.jpg',
                subtitle:  ' کفش رزا  ' ,
                category: 'girls',
                maincategory: 'shoes',
                subcategory: '',
                price: '410,000 تومان',
                img: './images/image-girls/shoes/kafsh-girl-4.jpg',
                desc:'دارای رویه نرم و مقاوم از جنس اسکارلت بوده و بند دار که روی بند نگین کار شده است. دارای زیره ضد سایش و ضد لغزش، قابل شستشو و تمیز شدن با دستمال نم دار/بسیار راحت و سبک و با دوام ',
                material:'نوعی کفش تخت  '
                },  
                {
                  id: 22,
                  title: 'kafsh-girl-5.jpg',
                  subtitle:  'کفش نیل ' ,
                  category: 'girls',
                  maincategory: 'shoes',
                  subcategory: '',
                  price: '355,000 تومان',
                  img: './images/image-girls/shoes/kafsh-girl-5.jpg',
                  desc:'دارای رویه نرم و مقاوم از جنس ورنی با طرح پاپیون اسکارلت در قسمت جلوی کفش  و زیره ضد سایش و ضد لغزش، دارای بند چسبی در قسمت رویه جهت پوشیدن راحت تر و تنظیم راحت تر، فوق العاده سبک، راحت و بادوام. ',
                  material:'نوعی کفش تخت  '
                  },
                  {
                    id: 23,
                    title: 'kafsh-girl-6.jpg',
                    subtitle:  'کفش نیل ' ,
                    category: 'girls',
                    maincategory: 'shoes',
                    subcategory: '',
                    price: '355,000 تومان',
                    img: './images/image-girls/shoes/kafsh-girl-6.jpg',
                    desc:'دارای رویه نرم و مقاوم از جنس ورنی با طرح پاپیون اسکارلت در قسمت جلوی کفش  و زیره ضد سایش و ضد لغزش، دارای بند چسبی در قسمت رویه جهت پوشیدن راحت تر و تنظیم راحت تر، فوق العاده سبک، راحت و بادوام. ',
                    material:'نوعی کفش تخت  '
                    }, 
                        
]